server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 127.0.0.1:8848 #nacos地址配置
        server-addr: 192.168.174.133:1111   #nginx负载注册地址

##暴露端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
