server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务名

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gitee_zhangh/springcloud-config.git #Gitee上面的git仓库名字
          ####搜索目录
          search-paths:
            - config
      ####读取分支
      label: master
  #########rabbitmq相关配置###############
  rabbitmq:
    host: 192.168.174.133
    port: 5672
    username: root
    password: root


#服务注册进Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

######暴露rabbitmq相关配置，暴露bus刷新配置的端点#######
management:
  endpoints:
    web:
      exposure:
        include: "*"    #暴露bus-refresh,springboot2.0之后为了安全，端口只暴露了health相关的健康检查端口，所以需要手动暴露bus相关的端口
