server:
  port: 7002
  
eureka:
  instance:
    hostname: eureka7002.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不想注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索实例
    service-url:
      #Eureka集群，相互守望，指向其他的Eureka
      defaultZone:  http://localhost:7001/eureka/
    server:
      #关闭自我保护机制，保证不可用服务及时被踢除
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 2000
