server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: prex_tx_group
    nacos:
      discovery:
        server-addr: 192.168.174.133:1111
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.174.133:3306/seata_order
      username: root
      password: 1234

feign:
  hystrix:
    enable : false

logging:
  level:
    seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
