server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-service  #服务名

eureka:
  client:
    ##是否将自己注册进Eureka
    register-with-eureka: true
    ##是否从EurekaService抓取已注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka

  instance:
    instance-id: paymentHystrix8001
    prefer-ip-address: true  # 访问路径可以显示ip
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
